name: newsbot

services:
  panel:
    environment:
      ADMIN_HTTPS_ONLY: "true"
    ports: []
    expose:
      - "8000"
    networks:
      - default
      - proxy

  bot:
    networks:
      - default

networks:
  proxy:
    external: true
    name: forestmessenger_app_network
